### ISSUE TITLE
Repo Secrets should not be case-sensitive on repo/org name

### ISSUE THREAD

**Issue by michaelschlies** [go-vela/server#120]
## Description

Repo Secrets should not be case-sensitive on repo/org name

## Value

Case insensitive matching for the same source code management platform will reduce negative interactions between users and webhooks.

## Definition of Done

`vela get secret --engine native --type repo --org GitHub --repo octoCat`
yields the same results as 
`vela get secret --engine native --type repo --org GITHUB --repo OCTOCAT`
or
`vela get secret --engine native --type repo --org github --repo octocat`

## Effort  (Optional)

_Estimated effort to complete this story? (Best Guess e.g. 1-2 days)_

## Impacted Personas (Optional)

Users

**Comment by kneal** [comment]
Hey @michaelschlies 

Thanks for the issue! I believe we may have slight differences of opinion on this one but I'm open to ideas. Today, the reason its case sensitive is because of the VCS providers that may be hooked up to the Vela server may be case sensitive.

For example, GitHub uses case sensitivity on organization and repository name. So in order for secrets to be properly, ACL'd to an organization and repository you need to ensure they match the upstream source.

**Comment by jbrockopp** [comment]
This work effort will not be completed due to the underlying VCS systems having case sensitive requirements.

**Comment by michaelschlies** [comment]
Fair. Thank you.
